[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]

# Compiler settings
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Network settings
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"