name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup demo environment
        run: |
          echo "NEXT_PUBLIC_THIRDWEB_CLIENT_ID=${{ secrets.DEMO_THIRDWEB_CLIENT_ID }}" >> .env.local
          echo "NEXT_PUBLIC_TIPPING_CONTRACT=0x0000000000000000000000000000000000000000" >> .env.local
          echo "NEXT_PUBLIC_STREAMER_REGISTRY=0x0000000000000000000000000000000000000000" >> .env.local
          echo "NEXT_PUBLIC_BRIDGE_CONTRACT=0x0000000000000000000000000000000000000000" >> .env.local
          echo "NEXT_PUBLIC_DEMO_MODE=true" >> .env.local
          
      - name: Prepare for static export
        run: |
          # Remove API routes and backend services for static export
          rm -rf src/app/api
          rm -f src/lib/settlement-service.ts
          rm -f src/lib/bridge.ts  
          rm -f src/lib/batch-processor.ts
          rm -f src/lib/monitoring.ts

      - name: Update Next.js config for demo
        run: |
          cat > next.config.js << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            basePath: '/thirdweb-tippingchain',
            assetPrefix: '/thirdweb-tippingchain',
            images: {
              unoptimized: true
            },
            trailingSlash: true,
            eslint: {
              ignoreDuringBuilds: true,
            },
            typescript: {
              ignoreBuildErrors: true,
            }
          }
          
          module.exports = nextConfig
          EOF
      
      - name: Build application
        run: |
          npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /thirdweb-tippingchain
          NEXT_PUBLIC_DEMO_MODE: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4